### ISSUE TITLE
Add OpenStreetMap copyright

### ISSUE THREAD

**Issue by luka1199** [luka1199/geo-heatmap#14]
Suggested by https://www.reddit.com/r/dataisbeautiful/comments/e2zv4w/i_wrote_a_python_script_that_generates_a_geo/f924sza?utm_source=share&utm_medium=web2x

https://www.openstreetmap.org/copyright/

**Comment by tanmaypandey7** [comment]
Is it weird that I am getting the OpenStreetMap copyright? 
![Screenshot from 2019-11-29 21-43-37](https://user-images.githubusercontent.com/36691630/69881016-9e459500-12f1-11ea-881b-d85c9794b24d.png)

The ODbl has a copyright link too
![Screenshot from 2019-11-29 21-46-55](https://user-images.githubusercontent.com/36691630/69881103-fa101e00-12f1-11ea-8a99-1df133e08dc6.png)

Does something else need to be added?

**Comment by luka1199** [comment]
Oh you are right. I didn't really check since someone on reddit suggested it. So I assumed it was missing.
