### ISSUE TITLE
Create a Flask App for easier interaction

### ISSUE THREAD

**Issue by tanmaypandey7** [luka1199/geo-heatmap#19]
WIP. All data will be processed instantly without including a SQL or any such database to store any form of data.

**Comment by luka1199** [comment]
Awesome! It would probably be best to do it in a seperate project so that the functionality of this project stays the same.

**Comment by tanmaypandey7** [comment]
Yeah thats cool too, although AFAIK only two extra files will be required, app.py and templates directory. Functionality of this project wont be modified in any way, too. You can check my previous work I did [here](https://github.com/tanmaypandey7/Simple-Flask-Project). 
We can make it a seperate project too, mostly it will depend on how the final code looks like.

**Comment by luka1199** [comment]
I think the repo you sent is private.

**Comment by luka1199** [comment]
I think it would be better to separate the projects.

**Comment by tanmaypandey7** [comment]
Sorry, link should work now.

**Comment by luka1199** [comment]
Would it be ok if I create the project and add you as a collaborator or do you want to create the project?

**Comment by tanmaypandey7** [comment]
You can add me, thats cool.

**Comment by luka1199** [comment]
https://github.com/luka1199/geo-heatmap-flask/invitations
