### ISSUE TITLE
Still getting MemoryError after installing a 64bit version

### ISSUE THREAD

**Issue by askaraboz** [luka1199/geo-heatmap#27]
Does it mean I need a more powerful computer?

**Comment by luka1199** [comment]
How big is you location file and how much RAM does your computer have?
I will probably add an option to stream in the data in the future (will be much slower but better for memory).

**Comment by askaraboz** [comment]
Location file is 745Mb and I have 6Gb of RAM. I couldn't find an option to download location data for just a year or a month.

**Comment by luka1199** [comment]
My file is 259 MB and I have 8GB RAM. For me the script uses 1.2 GB. So for you it would probably use about 3.4 GB which could exceed the memory limit.

**Comment by luka1199** [comment]
I'll try to implement the stream option as soon as I have time. If someone else wants to implement it feel free to submit a pull request :smiley:

**Comment by luka1199** [comment]
#20

**Comment by luka1199** [comment]
Pull (`git pull`) the new changes and run the command like this: 
```bash
python geo_heatmap.py -s <file>
```

**Comment by askaraboz** [comment]
Hey man I'm a beginner how do I implement git pull? Does that mean just reclone repository? THanks for your help!

**Comment by luka1199** [comment]
You can just reclone the repository or alternatively if you want to do it properly you can navigate to the directory containing the repository's files (as described in the instructions) and run the command ```git pull```.

**Comment by askaraboz** [comment]
I've tried the git pull option but its says 'git' is not recognized as an internal or external command,
operable program or batch file. I'm dong it in the command prompt in the folder where I have repository files, is that correct?

**Comment by askaraboz** [comment]
Oh wait I don't have git installed. I guess I was doing it wrong then :)

**Comment by askaraboz** [comment]
It worked great after cloning repository. Took about 8 minutes or so. Thank you!
How do I do it for only certain dates? do I just type in geo_heatmap.py - s [--min-date YYYY-MM-DD]
                      [--max-date YYYY-MM-DD] <file>
Also is there a way to use googles maps or not?

**Comment by luka1199** [comment]
To set a range of dates you run it like this:
```bash
python geo_heatmap.py -s --min-date <YYYY-MM-DD> --max-date <YYYY-MM-DD> <file>
```
(The square brackets in the usage output just mean that they are optional)

Example:
```bash
python geo_heatmap.py -s --min-date 2017-12-01 --max-date 2018-05-10 locations.json
```
Right now Google maps is not supported but will be maybe added in the future.
