### ISSUE TITLE
When running under WSL, heatmap.html opens in w3m browser

### ISSUE THREAD

**Issue by Kyle-Falconer** [luka1199/geo-heatmap#3]
The line that opens heatmap.html in the default browser doesn't work when running the program in the Windows Subsystem For Linux (WSL). This is because the default browser in WSL is w3m, a text-only browser.

This is the line that causes the issue: https://github.com/luka1199/geo-heatmap/blob/master/geo_heatmap.py#L83

It would be nice if the output didn't automatically open in a browser, but instead notifies over standard output what file was created.

Here's a screenshot of what the result looks like:
![heatmap screenshot](https://user-images.githubusercontent.com/1034255/69455635-afa10700-0d1d-11ea-8139-8fd08dcf55d0.PNG)

**Comment by luka1199** [comment]
Can you check if 2185d6f fixed this for you?

**Comment by Kyle-Falconer** [comment]
Yup, works fine. I like the solution.
