### ISSUE TITLE
progressbar error whilst streaming json file

### ISSUE THREAD

**Issue by stefanvds1** [luka1199/geo-heatmap#31]
once the json file has finished streaming, i immediately get the following error:
 Value 2528098 is out of range, should be between 0 and 2528097.328244275 
at      pb.update(i) line 86

**Comment by luka1199** [comment]
The problem is, that I estimate the number of locations before streaming the data. I will try to fix it.

**Comment by luka1199** [comment]
I think I fixed it with c932fa9. Can you check if it works for you now?

**Comment by jace** [comment]
Came here to report this exact same issue. The latest commits fix it.
