### ISSUE TITLE
Combine multiple location data files

### ISSUE THREAD

**Issue by nakami** [luka1199/geo-heatmap#32]
It would be nice to be able to call the script with multiple files and merge the timestamps all together.

**Comment by luka1199** [comment]
It is possible:
```bash
python geo_heatmap.py <file1> <file2> <file3> ...
```

**Comment by luka1199** [comment]
I added this to the [FAQ](https://github.com/luka1199/geo-heatmap/blob/master/README.md#faq) in the README.md since a couple of people didn't know about this feature.

**Comment by nakami** [comment]
Forgive me, I jumped to conclusions when I reached a certain point in the README.md:

> ### 5. Run the Script
> 
> In the same command prompt or Terminal window, type the following, and press enter:
> 
> ```shell
> python geo_heatmap.py <file>
> ```

May I suggest even using that notation there as well?

```shell
python geo_heatmap.py <file> [<file> ...]
```

**Comment by luka1199** [comment]
I added it to the README. I also added some examples for inexperienced users.
