### ISSUE TITLE
Could not locate runnable browser

### ISSUE THREAD

**Issue by dbranham20** [luka1199/geo-heatmap#36]
Hello, I currently have Firefox dev, Firefox, and Chrome on my computer and I was given the error: 
```
Traceback (most recent call last):
  File "geo_heatmap.py", line 251, in <module>
    if not isTextBasedBrowser(webbrowser.get()):
  File "/usr/lib/python3.6/webbrowser.py", line 51, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
```
I this might be a problem because I am running Windows Subsystem for Linux, making the installing paths of my applications a little weird. There is an option in webbrowser that allows for registration of a browser and it accepts a hard-coded path for the browser, but I don't see this as working generally enough for everbody.

**Comment by SuperSandro2000** [comment]
I think it tries to open x-www-browser which is specific to Linux. Just open the html file it generated by hand.

**Comment by luka1199** [comment]
I added some outputs that handle this error (04c7cd88b192e18b68b82bfe4f53f26bdf8224fd)
