### ISSUE TITLE
Remove personal information

### ISSUE THREAD

**Issue by jamesjarvis** [luka1199/geo-heatmap#41]
Probably worth mentioning that you have stored your own location history in a few of the commits. I'd recommend following these steps: https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

This can be personal information and would be best not to end up in the wrong hands!

**Comment by luka1199** [comment]
Thanks for pointing that out. I removed them from the history.

**Comment by jamesjarvis** [comment]
Nice 👍

**Comment by SuperSandro2000** [comment]
Keep in mind that any local copy still has the information.
