### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by rrggrr** [luka1199/geo-heatmap#8]
`File "geo-heatmap/geo_heatmap.py", line 104, in <module>
    generator.run(data_file, output_file)
  File "geo-heatmap/geo_heatmap.py", line 77, in run
    self.loadData(data_file)
  File "geo-heatmap/geo_heatmap.py", line 28, in loadData
    data = json.load(json_file)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by luka1199** [comment]
Can you send me the first 20 lines of your json file? (You can replace the "latitudeE7" and "longitudeE7" values with some symbols for your privacy)

**Comment by rrggrr** [comment]
I can send it encrypted via Keybase.io if you have an account? Otherwise I need an email or something to send it securely.

**Comment by luka1199** [comment]
luka.steinbach@gmx.de

**Comment by luka1199** [comment]
Somehow your file is not in JSON format or rather has non-JSON conforming quoting. Is this exactly how the file was in the ZIP archive?

**Comment by luka1199** [comment]
The format should look like this:
```
{
    "locations": [{
        "timestampMs": ...,
        "latitudeE7": ...,
        "longitudeE7": ...,
        "accuracy": ...,
        "activity": [{
            "timestampMs": ...,
            "activity": [{
                    "type": ...,
                    "confidence": ...
                },
                {
                    "type": "UNKNOWN",
                    "confidence": ...
                },
                {
                    "type": "IN_VEHICLE",
                    "confidence": ...
                },
                {
                    "type": "ON_FOOT",
                    "confidence": ...
                },
                {
                    "type": "UNKNOWN",
                    "confidence": ...
                }
            ]
        }]
    }]
}
```

**Comment by russellvt** [comment]
You _might_ try using "[jq](https://stedolan.github.io/jq/)" to try to track down the problem, directly, as-well. Most Linuxes have the binary in their distro's repository... it's pretty much a lifesaver with complex JSON.
