### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'max_value'

### ISSUE THREAD

**Issue by jk31** [luka1199/geo-heatmap#9]
Followed the steps, had to install `folium` and `progreessbar`, using python 3.7 on an anaconda env

```$ 
python geo_heatmap.py Standortverlauf.json
Loading data from Standortverlauf.json...
Traceback (most recent call last):
  File "geo_heatmap.py", line 111, in <module>
    generator.run(data_file, output_file)
  File "geo_heatmap.py", line 83, in run
    self.loadData(data_file)
  File "geo_heatmap.py", line 34, in loadData
    widgets=w) as pb:
TypeError: __init__() got an unexpected keyword argument 'max_value'
```

**Comment by luka1199** [comment]
Try to run:
```
pip uninstall progressbar
pip install progressbar2
```

You probably have progressbar installed, which uses `maxval` as an argument for `__init__`. Progressbar2 uses `max_value`.

**Comment by jk31** [comment]
Thanks it works now. 👍

**Comment by mikechen66** [comment]
> Try to run:
> 
> ```
> pip uninstall progressbar
> pip install progressbar2
> ```
> 
> You probably have progressbar installed, which uses `maxval` as an argument for `__init__`. Progressbar2 uses `max_value`.

Thanks. It works

**Comment by deadpool-liu** [comment]
there the error I meet when loading my paddle modle.But i don't know what happended. and this only happend in some modles.


TypeError                                 Traceback (most recent call last)
<ipython-input-9-cdc97ca038e4> in <module>
     20 
     21 mot = "4"
---> 22 model = pdx.load_model('./test/MOT20-0{}/YOLOv3/home/aistudio/work/YOLOv3/best_model/'.format(mot))
     23 # model.evaluate(eval_dataset, batch_size=1, epoch_id=None, metric=None, return_details=False)

E:\ProgramData\Anaconda3\lib\site-packages\paddlex\cv\models\load_model.py in load_model(model_dir, fixed_input_shape)
    125         else:
    126             model.test_transforms = build_transforms(
--> 127                 model.model_type, info['Transforms'], to_rgb)
    128             model.eval_transforms = copy.deepcopy(model.test_transforms)
    129 

E:\ProgramData\Anaconda3\lib\site-packages\paddlex\cv\transforms\__init__.py in build_transforms(model_type, transforms_info, to_rgb)
     36                 "There's no operator named '{}' in transforms of {}".format(
     37                     op_name, model_type))
---> 38         transforms.append(getattr(T, op_name)(**op_attr))
     39     eval_transforms = T.Compose(transforms)
     40     eval_transforms.to_rgb = to_rgb

TypeError: __init__() got an unexpected keyword argument 'max_val'

**Comment by luka1199** [comment]
Is this related to [geo-heatmap](https://github.com/luka1199/geo-heatmap) or are you running something else?
This repository has nothing to do with [Paddle](https://github.com/PaddlePaddle/Paddle).

**Comment by ShubhamJagtap2000** [comment]
In Jupyter Lab, it is still showing the same error with progressbar and progressbar2, I tried after uninstalling progressbar
